CREATE DATABASE KRTBankDb;
GO

USE KRTBankDb;
GO

CREATE TABLE Accounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    HolderName NVARCHAR(200) NOT NULL,
    CPF NVARCHAR(11) NOT NULL,
    IsActive BIT NOT NULL
);
